export const project = [
    {
    id:1,
    name: "fragen",
    visit: 21,
    process: "100%",
    date: "01/12/2022",
    license: "free",
    header: "Aplicación realizada durante el curso de aprendizaje en The Bridge",
    descriptions: "",
    created_by: "The bridge",
    github: 'https://github.com/orgs/TheBridge-Sevilla/repositories'
    },
    {
    id:2,
    name: "Marvel",
    visit: 32,
    process: "100%",
    date: "01/01/2023",
    license: "free",
    header: "Aplicación presentada en el Desafío Tripulación The Bridge",
    descriptions: "",
    created_by: "The bridge",
    github: 'https://github.com/orgs/TheBridge-Sevilla/repositories',
    youtube: 'https://youtu.be/ZKiWECYqbhc'
    },
    {
    id:3,
    name: "vinoApp",
    visit: 8,
    process: "25%",
    date: "13/06/2024",
    license: "MIT license",
    header: "Aplicación del Trabajo Fin de Ciclo de DAM",
    descriptions: "",
    created_by: "idavid80",
    github: 'https://github.com/idavid80/Proyecto_TFC',
    presentation: 'https://www.canva.com/design/DAGHb6A1mdY/7kdQgMME8Gt7QjtWzoAs2g/view?utm_content=DAGHb6A1mdY&utm_campaign=designshare&utm_medium=link&utm_source=editor',
    },
    {
    id:4,
    name: "1º DAM",
    visit: 2,
    process: "100%",
    date: "19/06/2023",
    license: "free",
    header: "Ejercicios sobre programación del primer año de DAM",
    descriptions: "",
    created_by: "idavid80",
    github: 'https://github.com/idavid80/introduccion_JAVA'
    },
    {
    id:5,
    name: "2º DAM",
    visit: 3,
    process: "100%",
    date: "28/02/2024",
    license: "free",
    header: "Ejercicios sobre programación del segundo año de DAM",
    descriptions: "",
    created_by: "idavid80",
    github: 'https://github.com/idavid80/acceso_datos_2'
    },
    {
    id:6,
    name: "Restaurant Lemon",
    visit: 15,
    process: "100%",
    date: "31/10/2023",
    license: "free",
    header: "Proyecto final del curso de Meta Front-end",
    descriptions: "",
    created_by: "idavid80",
    github: 'https://github.com/idavid80/react-meta'
    },
    {
    id:7,
    name: "Python Automatización",
    visit: 4,
    process: "100%",
    date: "31/10/2023",
    license: "free",
    header: "Proyecto final del curso de Google Python",
    descriptions: "",
    created_by: "idavid80",
    github: 'https://github.com/idavid80/Learning_python'
    },
    {
    id:8,
    name: "Curso IBM DataScience",
    visit: 8,
    process: "100%",
    date: "13/11/2024",
    license: "free",
    header: "Proyecto final del curso de IBM DataScience",
    descriptions: "Certificado Profesional en Ciencia de Datos es un programa de 12 cursos diseñado para prepararte para una carrera como científico de datos",
    created_by: "idavid80",
    github: 'https://github.com/idavid80/DataScience'
        }
];